import type { AgentConfig } from "../core/schema.js";
import type { GeneratedFile, HarnessGenerator } from "./types.js";
import { ruleBody } from "./shared.js";

/**
 * Codex's default MCP startup timeout is 10s; `npx -y <pkg>` downloads the
 * package (~150 MB with ast-grep + tree-sitter grammars) on the first run and
 * the server was killed before it could answer `initialize`.
 */
const STARTUP_TIMEOUT_SEC = 120;

/** AGENTS.md + .codex/config.toml for Codex (FR-1.3) */
export const codexGenerator: HarnessGenerator = {
  harness: "codex",
  generate(config: AgentConfig): GeneratedFile[] {
    const lines = ruleBody(config, "codex");

    // Codex MCP registration: config.toml [mcp_servers.<name>].
    // JSON string escapes are valid TOML basic-string escapes, so JSON.stringify
    // keeps Windows paths (C:\Users\...) and embedded quotes intact.
    const str = (v: string) => JSON.stringify(v);
    const key = (k: string) => (/^[A-Za-z0-9_-]+$/.test(k) ? k : str(k));
    const toml = [
      `# Generated by agentos — edit agent.config.yaml, then run "agentos sync"`,
      ...config.mcpServers.flatMap((s) => {
        const envLines = s.env
          ? Object.entries(s.env).map(([k, v]) => `${key(k)} = ${str(v)}`)
          : [];
        return [
          `[mcp_servers.${key(s.name)}]`,
          `command = ${str(s.command)}`,
          `args = [${s.args.map(str).join(", ")}]`,
          `startup_timeout_sec = ${STARTUP_TIMEOUT_SEC}`,
          ...(envLines.length ? [``, `[mcp_servers.${key(s.name)}.env]`, ...envLines] : []),
          ``,
        ];
      }),
    ].join("\n");

    return [
      { path: "AGENTS.md", content: lines.join("\n") },
      { path: ".codex/config.toml", content: toml },
    ];
  },
};
