import type { AgentConfig } from "../core/schema.js";
import { rulesForHarness } from "../core/schema.js";
import type { GeneratedFile, HarnessGenerator } from "./types.js";

/** AGENTS.md + .codex/config.toml for Codex (FR-1.3) */
export const codexGenerator: HarnessGenerator = {
  harness: "codex",
  generate(config: AgentConfig): GeneratedFile[] {
    const rules = rulesForHarness(config, "codex");
    const lines: string[] = [
      `# ${config.project.name}`,
      "",
      config.project.description ?? "",
      "",
    ];
    if (config.stack.length) {
      lines.push(`**Stack:** ${config.stack.join(", ")}`, "");
    }
    if (rules.length) {
      lines.push("## Rules", "");
      for (const r of rules) lines.push(`- **${r.id}:** ${r.text}`);
      lines.push("");
    }
    lines.push(
      "## Local Tools (AgentOS)",
      "",
      "Deterministic tools are available via MCP — prefer them over guessing:",
      "- `memory` — store/recall project facts",
      "- `supersearch` — text/symbol/git-history search",
      "- `codegraph` — dependency graph + change impact",
      "",
    );

    // Codex MCP registration: config.toml [mcp_servers.<name>].
    // JSON string escapes are valid TOML basic-string escapes, so JSON.stringify
    // keeps Windows paths (C:\Users\...) and embedded quotes intact.
    const str = (v: string) => JSON.stringify(v);
    const key = (k: string) => (/^[A-Za-z0-9_-]+$/.test(k) ? k : str(k));
    const toml = [
      `# Generated by agentos — edit agent.config.yaml, then run "agentos sync"`,
      ...config.mcpServers.flatMap((s) => {
        const envLines = s.env
          ? Object.entries(s.env).map(([k, v]) => `${key(k)} = ${str(v)}`)
          : [];
        return [
          `[mcp_servers.${key(s.name)}]`,
          `command = ${str(s.command)}`,
          `args = [${s.args.map(str).join(", ")}]`,
          ...(envLines.length ? [``, `[mcp_servers.${key(s.name)}.env]`, ...envLines] : []),
          ``,
        ];
      }),
    ].join("\n");

    return [
      { path: "AGENTS.md", content: lines.join("\n") },
      { path: ".codex/config.toml", content: toml },
    ];
  },
};
