import { writeFileSync, mkdirSync, existsSync, readFileSync, copyFileSync, rmSync } from "node:fs";
import path from "node:path";
import { loadConfig } from "../core/loader.js";
import { generators } from "../generators/index.js";
import { writeManifest, hashContent, readManifest, detectDrift, type ManifestEntry } from "../core/manifest.js";
import type { HarnessName } from "../core/schema.js";

export interface SyncOptions {
  cwd?: string;
  /** Only sync these harnesses */
  only?: HarnessName[];
  /** Overwrite drifted (hand-edited) and pre-existing files; the previous version is kept as <file>.bak */
  force?: boolean;
  quiet?: boolean;
}

const log = (msg: string, quiet?: boolean) => { if (!quiet) console.log(msg); };

export function sync(options: SyncOptions = {}): void {
  const cwd = options.cwd ?? process.cwd();
  const { config, sources } = loadConfig(cwd);
  const targets = options.only ?? (Object.keys(generators) as HarnessName[]);

  // FR-7.3: inject the latest handoff into generated markdown configs (.md and
  // Cursor's .mdc) so the target harness auto-receives pending context.
  const handoffPath = path.join(cwd, "HANDOFF.md");
  const handoff = existsSync(handoffPath) ? readFileSync(handoffPath, "utf8") : null;

  const planned: { path: string; content: string }[] = [];
  for (const h of targets) {
    for (const file of generators[h].generate(config)) {
      planned.push({
        path: file.path,
        content: handoff && /\.mdc?$/.test(file.path)
          ? file.content + "\n## Active Handoff (AgentOS)\n\n" + handoff
          : file.content,
      });
    }
  }

  // FR-1.6: never silently destroy someone's work.
  //   drifted   = a file we generated earlier that was hand-edited since
  //   unmanaged = a file we never generated that already exists with other content
  //               (the hand-written CLAUDE.md of a project adopting agentos)
  const manifest = readManifest(cwd);
  const managed = new Set((manifest?.files ?? []).map((f) => f.path));
  const plannedPaths = new Set(planned.map((f) => f.path));
  const drifted = detectDrift(cwd).drifted.filter((p) => plannedPaths.has(p));
  const unmanaged = planned
    .filter((f) => !managed.has(f.path))
    .filter((f) => {
      const abs = path.join(cwd, f.path);
      return existsSync(abs) && readFileSync(abs, "utf8") !== f.content;
    })
    .map((f) => f.path);

  if (!options.force) {
    if (drifted.length) {
      throw new Error(
        `Drift detected in:\n  ${drifted.join("\n  ")}\n\n` +
          `These files were edited by hand after the last sync.\n` +
          `Re-run with --force to overwrite (the current version is kept as <file>.bak), or move your edits into agent.config.yaml.`,
      );
    }
    if (unmanaged.length) {
      throw new Error(
        `Existing files would be overwritten:\n  ${unmanaged.join("\n  ")}\n\n` +
          `They were not generated by agentos. Move their content into agent.config.yaml (rules, description),\n` +
          `then re-run with --force — the originals are kept as <file>.bak.`,
      );
    }
  }

  // keep manifest entries for harnesses not part of this run (sync --only)
  const entries = new Map<string, ManifestEntry>((manifest?.files ?? []).map((f) => [f.path, f]));
  const backup = new Set([...drifted, ...unmanaged]);
  for (const file of planned) {
    const abs = path.join(cwd, file.path);
    mkdirSync(path.dirname(abs), { recursive: true });
    if (backup.has(file.path)) copyFileSync(abs, abs + ".bak");
    writeFileSync(abs, file.content);
    const hash = hashContent(file.content);
    entries.set(file.path, { path: file.path, generatedHash: hash, writtenHash: hash });
    log(`  ✓ ${file.path}${backup.has(file.path) ? `  (previous version → ${file.path}.bak)` : ""}`, options.quiet);
  }
  // A target that moved (Antigravity's config path did) leaves its old file behind:
  // on a full sync, remove files we generated earlier that no generator produces
  // any more — but only if they are byte-for-byte what we wrote.
  if (!options.only) {
    for (const [p, entry] of [...entries]) {
      if (plannedPaths.has(p)) continue;
      const abs = path.join(cwd, p);
      if (existsSync(abs) && hashContent(readFileSync(abs, "utf8")) === entry.generatedHash) {
        rmSync(abs);
        log(`  − ${p}  (no longer generated)`, options.quiet);
      } else if (existsSync(abs)) {
        log(`  ⚠ ${p} is no longer generated but was edited by hand — left in place`, options.quiet);
      }
      entries.delete(p);
    }
  }
  writeManifest(cwd, [...entries.values()]);
  log(`Synced ${planned.length} files from ${sources.length} config source(s).`, options.quiet);
}

export { detectDrift, readManifest };
